apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fastapi-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - fastapi-prod
  selector:
    matchLabels:
      app.kubernetes.io/name: fastapi-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
