sonar.projectKey=devops-gitops-pipeline
sonar.projectName=DevOps GitOps Pipeline
sonar.projectVersion=1.0

sonar.sources=app
sonar.tests=app/tests
sonar.language=py
sonar.python.coverage.reportPaths=app/coverage.xml
sonar.python.version=3.12

sonar.exclusions=**/__pycache__/**,**/*.pyc,**/tests/**
sonar.test.inclusions=**/tests/**

# Quality Gate: fail if coverage < 70%
sonar.coverage.exclusions=**/tests/**
